services:
    Bigz\ApiDocDumperBundle\Command\DumpApiDocCommand:
        public: true
        tags:
            - { name: console.command }
        arguments:
            - '@nelmio_api_doc.generator'
